import { IngredientInsertDto } from 'src/ingredients/dto/ingredients.dto';

export const ingredient_seed: IngredientInsertDto[] = [
  {
    name: 'Tequila',
    type: 'alcohol',
    imageURL: 'ingredients/tequila_image.jpeg',
    description: 'Distilled spirit made from blue agave.',
    isMainAlcohol: true,
  },
  {
    name: 'Lime juice',
    type: 'juice',
    imageURL: 'ingredients/lime_juice_image.jpeg',
    description: 'Juice from limes.',
    isMainAlcohol: false,
  },
  {
    name: 'Triple sec',
    type: 'alcohol',
    imageURL: 'ingredients/triple_sec_image.jpeg',
    description: 'Orange-flavored liqueur.',
    isMainAlcohol: false,
  },
  {
    name: 'Rum',
    type: 'alcohol',
    imageURL: 'ingredients/rum_image.jpeg',
    description: 'Spirit distilled from sugarcane.',
    isMainAlcohol: true,
  },
  {
    name: 'Mint',
    type: 'garnish',
    imageURL: 'ingredients/mint_image.jpeg',
    description: 'Aromatic herb.',
    isMainAlcohol: false,
  },
  {
    name: 'Sugar',
    type: 'syrup',
    imageURL: 'ingredients/sugar_image.jpeg',
    description: 'Sweetener.',
    isMainAlcohol: false,
  },
  {
    name: 'Soda water',
    type: 'carbonated',
    imageURL: 'ingredients/soda_water_image.jpeg',
    description: 'Carbonated water.',
    isMainAlcohol: false,
  },
  {
    name: 'Bourbon whiskey',
    type: 'alcohol',
    imageURL: 'ingredients/bourbon_whiskey_image.jpeg',
    description: 'American whiskey from corn.',
    isMainAlcohol: true,
  },
  {
    name: 'Angostura bitters',
    type: 'others',
    imageURL: 'ingredients/angostura_bitters_image.jpeg',
    description: 'Bitter, herbal flavoring.',
    isMainAlcohol: false,
  },
  {
    name: 'Whiskey',
    type: 'alcohol',
    imageURL: 'ingredients/whiskey_image.jpeg',
    description: 'Distilled alcoholic beverage from grain.',
    isMainAlcohol: true,
  },
  {
    name: 'Sweet vermouth',
    type: 'alcohol',
    imageURL: 'ingredients/sweet_vermouth_image.jpeg',
    description: 'Fortified, sweetened wine.',
    isMainAlcohol: false,
  },
  {
    name: 'Gin',
    type: 'alcohol',
    imageURL: 'ingredients/gin_image.jpeg',
    description: 'Spirit flavored with juniper.',
    isMainAlcohol: true,
  },
  {
    name: 'Vodka',
    type: 'alcohol',
    imageURL: 'ingredients/vodka_image.jpeg',
    description: 'Distilled spirit.',
    isMainAlcohol: true,
  },
  {
    name: 'Dry vermouth',
    type: 'alcohol',
    imageURL: 'ingredients/dry_vermouth_image.jpeg',
    description: 'Fortified, dry wine.',
    isMainAlcohol: false,
  },
  {
    name: 'Cranberry juice',
    type: 'juice',
    imageURL: 'ingredients/cranberry_juice_image.jpeg',
    description: 'Juice from cranberries.',
    isMainAlcohol: false,
  },
  {
    name: 'Pineapple juice',
    type: 'juice',
    imageURL: 'ingredients/pineapple_juice_image.jpeg',
    description: 'Juice from pineapples.',
    isMainAlcohol: false,
  },
  {
    name: 'Coconut cream',
    type: 'others',
    imageURL: 'ingredients/coconut_cream_image.jpeg',
    description: 'Cream from coconut milk.',
    isMainAlcohol: false,
  },
  {
    name: 'Tomato juice',
    type: 'juice',
    imageURL: 'ingredients/tomato_juice_image.jpeg',
    description: 'Juice from tomatoes.',
    isMainAlcohol: false,
  },
  {
    name: 'Lemon juice',
    type: 'juice',
    imageURL: 'ingredients/lemon_juice_image.jpeg',
    description: 'Juice from lemons.',
    isMainAlcohol: false,
  },
  {
    name: 'Worcestershire sauce',
    type: 'others',
    imageURL: 'ingredients/worcestershire_sauce_image.jpeg',
    description: 'Savory sauce.',
    isMainAlcohol: false,
  },
  {
    name: 'Tabasco sauce',
    type: 'others',
    imageURL: 'ingredients/tabasco_sauce_image.jpeg',
    description: 'Hot pepper sauce.',
    isMainAlcohol: false,
  },
  {
    name: 'Ginger beer',
    type: 'carbonated',
    imageURL: 'ingredients/ginger_beer_image.jpeg',
    description: 'Non-alcoholic ginger beverage.',
    isMainAlcohol: false,
  },
];
